### ISSUE TITLE
Website does not reflect files removed from the repo

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rust-forge#127]
E.g., https://forge.rust-lang.org/ides.html works, but ides.md was removed last year.

**Comment by dlukes** [comment]
Just an update on this, six months later: the link to ides.html doesn't work anymore, so the website has probably been updated and this issue can be closed...? The problem with this particular link is that the [FAQ](https://www.rust-lang.org/en-US/faq.html#debugging) still points to it -- it should probably be removed or updated (if there's a replacement).

**Comment by pietroalbini** [comment]
The page is not present anymore on forge.rust-lang.org, closing the issue.

> The problem with this particular link is that the FAQ still points to it -- it should probably be removed or updated (if there's a replacement).

That link should not be present anymore on the new website, which will be launched soon(tm).
