### ISSUE TITLE
Is there a plan to replace ides.md 

### ISSUE THREAD

**Issue by guest20** [rust-lang-nursery/rust-forge#154]
`ides.md` was removed in https://github.com/rust-lang-nursery/rust-forge/commit/aa1688d544c042f4d1024eba5efeb15012fbb2c8 but [the faq](https://www.rust-lang.org/en-US/faq.html#debugging) still refers to it.

Is there a plan to replace this, or a better place to find a list of ides?

**Comment by nrc** [comment]
There is no plan to replace ides.md in the forge. However, we do plan to have some detail on the new website about IDEs and other tools, this will happen sometime around the new edition.

**Comment by steveklabnik** [comment]
question answered, so closing. Thanks!
