### ISSUE TITLE
IDE page is duplicated on the rust-lang.org and the forge

### ISSUE THREAD

**Issue by matklad** [rust-lang-nursery/rust-forge#9]
* https://www.rust-lang.org/ides.html
* https://forge.rust-lang.org/ides.html

Perhaps there should be only one `ides.html`?

The first one seems more up to date (at least the info about intellij-rust is more fresh).

**Comment by matklad** [comment]
@alexcrichton ping

**Comment by alexcrichton** [comment]
@brson do you remember why there's duplication here? Maybe we should just delete the forge one?

**Comment by brson** [comment]
I intended to move the ides page to the forge. Either one can be deleted, but the website version doesn't use the website style.

**Comment by matklad** [comment]
rust-lang.org version now redirects here, and I've send a PR with an updated info about IntelliJ-Rust, so this can be closed then.
