### ISSUE TITLE
Access Denied to beta-backporting.html

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang-nursery/rust-forge#90]
https://forge.rust-lang.org/ has a link to https://forge.rust-lang.org/beta-backporting.html , which gives a `<Message>Access Denied</Message>` error.

**Comment by kennytm** [comment]
![sorry.](https://user-images.githubusercontent.com/103023/29634080-2f1611da-887b-11e7-923f-a078a21b113f.jpg)

**Comment by pietroalbini** [comment]
This has been fixed.
