### ISSUE TITLE
rustc internal docs

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-lang-nursery/rust-forge#98]
I've currently got a cron job set up to build the internal docs once or twice a day and upload them to github pages ([repo](https://github.com/Michael-F-Bryan/rustc-internal-docs)/[rendered](https://michael-f-bryan.github.io/rustc-internal-docs/)). @Manishearth has a [similar repository][mh], although it looks like it was updated manually so a couple things became outdated.

Is it worth either adding a link to my docs or setting up a [travis "cron" job][cron] so that we have the docs available for people hacking on the compiler internals?

[mh]: http://manishearth.github.io/rust-internals-docs/rustc/
[cron]: https://docs.travis-ci.com/user/cron-jobs/

**Comment by mgattozzi** [comment]
@Michael-F-Bryan I was trying to [set it up](https://github.com/mgattozzi/rust-forge/tree/compiler-docs) so forge could do this and have it available. I haven't had the time to work on it, but this is something that has been wanted and discussed before. Any help would be greatly appreciated

**Comment by jonas-schievink** [comment]
The forge now links to https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ - It looks up-to-date, is this done?
